# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('associacao', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('iata', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nome', models.CharField(max_length=120)),
                ('senha', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateTimeField()),
                ('duracao', models.IntegerField()),
                ('dinheiro_total', models.FloatField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Destino', to='viajante.Cidade')),
                ('origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origem', to='viajante.Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viajante.Pessoa')),
                ('telefone', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agencia', to='viajante.Agencia')),
            ],
            bases=('viajante.pessoa',),
        ),
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viajante.Pessoa')),
                ('idade', models.IntegerField()),
                ('dinheiro', models.FloatField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viajante.Tema', verbose_name='Tema')),
            ],
            bases=('viajante.pessoa',),
        ),
    ]
